name: 'Chromatic'
on: [pull_request]
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          allowConsoleErrors: true
  percy-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install packages
        run: yarn
      - name: Run visual testing
        # run: npx percy exec -- yarn cy:percy
        run: echo "run visual testing"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}